### PR TITLE
Add GitHub workflow for automated release of source archives and wheel on version tags

### PR DESCRIPTION
**Pull request by DragaDoncila**
This GitHub workflow runs on tags starting with `v`. It builds a wheel from the source code and cuts a release of the wheel & source code archives, named after the tag.

I would like to have the wheel available for local/outside AWS testing of the `plugins` lambda code.

I tested it on my own fork, and you can see the action run [here](https://github.com/DragaDoncila/napari-demo/runs/8263259531?check_suite_focus=true)

### CODE REVIEW

**Review by potating-potato — APPROVED** [review]
LGTM!

**Comment by potating-potato** [comment]
I just rememberd we do have a release workflow: https://github.com/chanzuckerberg/napari-demo/blob/main/.github/workflows/test_and_deploy.yml

but it does release to pypi, by any chance we can just do another release, maybe 0.5.0?

**Comment by DragaDoncila** [comment]
@potating-potato oops yeah, the cookiecutter does provide a deploy workflow. It looks like it uses `setup.py` to build, whereas we use the `build` package here which is recommended. Would you like me to replace the deploy step in the existing workflow with the build & release process here? I assume we don't ever want to be releasing this plugin to PyPI and would prefer to just cut github releases (as this is doing), but let me know if I'm wrong.

**Comment by potating-potato** [comment]
> Would you like me to replace the deploy step in the existing workflow with the build & release process here? 
Yes please!

> I assume we don't ever want to be releasing this plugin to PyPI and would prefer to just cut GitHub releases (as this is doing)
I can see both ways. Particularly since this plugin is on PyPI already anyway. at some point, we can certainly make it invisible for users, but for now, it is probably fine to keep releasing to PyPI so we can install it more easily for development purposes

**Comment by potating-potato** [comment]
@DragaDoncila I added the github release step from this PR to https://github.com/chanzuckerberg/napari-demo/pull/16/files

can you please take a look at the changes there? I added a few more things to clean up the plugin setup

**Comment by DragaDoncila** [comment]
@potating-potato perfect, closing this now and will review that one!

**Pull request closed without merging**
